/* DO NOT EDIT THIS FILE */

// baseline.c
// output the total time (compute, read time, write time)
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#include "mm.h"


#define SEC 1000000000L

unsigned long long elapsed(const struct timespec start, const struct timespec end) {
    struct timespec result;
    result.tv_sec = end.tv_sec - start.tv_sec;
    result.tv_nsec = end.tv_nsec - start.tv_nsec;
    if (result.tv_nsec < 0) {
        --result.tv_sec;
        result.tv_nsec += SEC;
    }
    unsigned long long res = result.tv_sec *1ULL* SEC + result.tv_nsec;
    return res;
}

void verify_mm_compute(){
    int T = 20;
    int i;
    srand(time(0));
    for(i=0;i<T;i++){
        MMData tmp;
        tmp.m = rand()%100+1;
        tmp.k = rand()%100+1;
        tmp.n = rand()%100+1;
        int *X = (int*) malloc(sizeof(int)*tmp.m*tmp.k);
        int *Y = (int*) malloc(sizeof(int)*tmp.k*tmp.n);
        int *Z = (int*) malloc(sizeof(int)*tmp.m*tmp.n);

        int j,l;
        for(j=0;j<tmp.m*tmp.k;j++){
            X[j] = rand()%100;
        }
        for(j=0;j<tmp.k*tmp.n;j++){
            Y[j] = rand()%100;
        }
        for(j=0;j<tmp.m*tmp.n;j++){
            Z[j] = 0;
        }
        tmp.X = X;
        tmp.Y = Y;
        tmp.Z = Z;

        mm_compute(&tmp);
        int *Z_ref = (int*) malloc(sizeof(int)*tmp.m*tmp.n);
        // calc Z_ref, Z_ref = X@Y
        for(j=0;j<tmp.m;j++){
            for(l=0;l<tmp.n;l++){
                int sum = 0;
                for(int k=0;k<tmp.k;k++){
                    sum += X[j*tmp.k+k] * Y[k*tmp.n+l];
                }
                Z_ref[j*tmp.n+l] = sum;
            }
        }
        // verify Z
        for(j=0;j<tmp.m*tmp.n;j++){
            if(Z[j] != Z_ref[j]){
                printf("verify mm_compute failed\n");
                printf("Z[%d] = %d, Z_ref[%d] = %d\n", j, Z[j], j, Z_ref[j]);
                exit(1);
            }
        }

        free(X);
        free(Y);
        free(Z);
        free(Z_ref);
    }
}

void solve(const char * in_path, const char * out_path){
    unsigned long long compute_time = 0, total_time = 0;
    struct timespec all_start, all_end;
    clock_gettime(CLOCK_MONOTONIC, &all_start);

    FILE *fp=fopen(in_path, "r");
    if(fp==NULL){
        printf("Error opening file\n");
        exit(1);
    }
    freopen(out_path, "w", stdout);
    int N, t;
    fscanf(fp, "%d", &N);
    for(t=0; t<N; t++){
        // input
        MMData data;
        load_MMData(fp, &data);

        // compute time
        struct timespec start, end;
        clock_gettime(CLOCK_MONOTONIC, &start);
        mm_compute(&data);
        clock_gettime(CLOCK_MONOTONIC, &end);
        compute_time += elapsed(start, end);

        // output
        print_MMData(&data);
    }

    fclose(fp);

    clock_gettime(CLOCK_MONOTONIC, &all_end);
    total_time = elapsed(all_start, all_end);

    fprintf(stderr, "compute_time %.2f total_time %.2f\n", compute_time*1./SEC, total_time*1./SEC);
}

int main(int argc, char *argv[]){
    if(argc != 3){
        printf("Usage: %s <input_path> <output_path>\n", argv[0]);
        exit(1);
    }
    verify_mm_compute();
    solve(argv[1], argv[2]);
    return 0;
}
